//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ineltur.WebService.NationalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ineltur.com/", ConfigurationName="NationalService.HotelesSoapSoap")]
    public interface HotelesSoapSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/BuscarDestinos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        Ineltur.WebService.NationalService.RespuestaBuscarDestinos BuscarDestinos(Ineltur.WebService.NationalService.PeticionBuscarDestinos peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/BuscarAlojamientos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        Ineltur.WebService.NationalService.RespuestaBuscarAlojamientos BuscarAlojamientos(Ineltur.WebService.NationalService.PeticionBuscarAlojamientos peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/InfoAlojamiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        Ineltur.WebService.NationalService.RespuestaInfoAlojamiento InfoAlojamiento(Ineltur.WebService.NationalService.PeticionInfoAlojamiento peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/InfoCuposAlojamiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        Ineltur.WebService.NationalService.RespuestaInfoCuposAlojamiento InfoCuposAlojamiento(Ineltur.WebService.NationalService.PeticionInfoCuposAlojamiento peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/ReservarAlojamiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        Ineltur.WebService.NationalService.RespuestaReservarAlojamiento ReservarAlojamiento(Ineltur.WebService.NationalService.PeticionReservarAlojamiento peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/CancelarReservaAlojamiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        Ineltur.WebService.NationalService.RespuestaCancelarReservaAlojamiento CancelarReservaAlojamiento(Ineltur.WebService.NationalService.PeticionCancelarReservaAlojamiento peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/ConsultarReservaAlojamiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        Ineltur.WebService.NationalService.RespuestaConsultarReservaAlojamiento ConsultarReservaAlojamiento(Ineltur.WebService.NationalService.PeticionConsultarReservaAlojamiento peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/BuscarAlojamientosEInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        Ineltur.WebService.NationalService.RespuestaBuscarAlojamientosEInfo BuscarAlojamientosEInfo(Ineltur.WebService.NationalService.PeticionBuscarAlojamientos peticion);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionBuscarDestinos : PeticionBase {
        
        private string destinoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionConsultarReservaAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionCancelarReservaAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionReservarAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionInfoAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionInfoCuposAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionBuscarAlojamientos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionBuscarDestinos))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public abstract partial class PeticionBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string claveField;
        
        private string idiomaDeseadoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdiomaDeseado {
            get {
                return this.idiomaDeseadoField;
            }
            set {
                this.idiomaDeseadoField = value;
                this.RaisePropertyChanged("IdiomaDeseado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoAlojamientoDisponibleCompleta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoDestino destinoField;
        
        private InfoAlojamiento alojamientoField;
        
        private System.Nullable<TipoAlojamiento> tipoAlojamientoField;
        
        private System.Nullable<System.Guid> idAlojamientoField;
        
        private string nombreField;
        
        private System.Nullable<Moneda> monedaField;
        
        private System.Nullable<decimal> tarifa1Field;
        
        private System.Nullable<decimal> tarifa2Field;
        
        private System.Nullable<decimal> tarifa3Field;
        
        private System.Nullable<decimal> tarifa4Field;
        
        private System.Nullable<decimal> tarifa5Field;
        
        private System.Nullable<decimal> tarifa6Field;
        
        private System.Nullable<int> cupo1Field;
        
        private System.Nullable<int> cupo2Field;
        
        private System.Nullable<int> cupo3Field;
        
        private System.Nullable<int> cupo4Field;
        
        private System.Nullable<int> cupo5Field;
        
        private System.Nullable<int> cupo6Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfoDestino Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InfoAlojamiento Alojamiento {
            get {
                return this.alojamientoField;
            }
            set {
                this.alojamientoField = value;
                this.RaisePropertyChanged("Alojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<TipoAlojamiento> TipoAlojamiento {
            get {
                return this.tipoAlojamientoField;
            }
            set {
                this.tipoAlojamientoField = value;
                this.RaisePropertyChanged("TipoAlojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.Guid> IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<Moneda> Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> Tarifa1 {
            get {
                return this.tarifa1Field;
            }
            set {
                this.tarifa1Field = value;
                this.RaisePropertyChanged("Tarifa1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> Tarifa2 {
            get {
                return this.tarifa2Field;
            }
            set {
                this.tarifa2Field = value;
                this.RaisePropertyChanged("Tarifa2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> Tarifa3 {
            get {
                return this.tarifa3Field;
            }
            set {
                this.tarifa3Field = value;
                this.RaisePropertyChanged("Tarifa3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> Tarifa4 {
            get {
                return this.tarifa4Field;
            }
            set {
                this.tarifa4Field = value;
                this.RaisePropertyChanged("Tarifa4");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> Tarifa5 {
            get {
                return this.tarifa5Field;
            }
            set {
                this.tarifa5Field = value;
                this.RaisePropertyChanged("Tarifa5");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> Tarifa6 {
            get {
                return this.tarifa6Field;
            }
            set {
                this.tarifa6Field = value;
                this.RaisePropertyChanged("Tarifa6");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> Cupo1 {
            get {
                return this.cupo1Field;
            }
            set {
                this.cupo1Field = value;
                this.RaisePropertyChanged("Cupo1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> Cupo2 {
            get {
                return this.cupo2Field;
            }
            set {
                this.cupo2Field = value;
                this.RaisePropertyChanged("Cupo2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> Cupo3 {
            get {
                return this.cupo3Field;
            }
            set {
                this.cupo3Field = value;
                this.RaisePropertyChanged("Cupo3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> Cupo4 {
            get {
                return this.cupo4Field;
            }
            set {
                this.cupo4Field = value;
                this.RaisePropertyChanged("Cupo4");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> Cupo5 {
            get {
                return this.cupo5Field;
            }
            set {
                this.cupo5Field = value;
                this.RaisePropertyChanged("Cupo5");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> Cupo6 {
            get {
                return this.cupo6Field;
            }
            set {
                this.cupo6Field = value;
                this.RaisePropertyChanged("Cupo6");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoDestino : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idDestinoField;
        
        private TipoDestino tipoDestinoField;
        
        private string nombreDestinoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdDestino {
            get {
                return this.idDestinoField;
            }
            set {
                this.idDestinoField = value;
                this.RaisePropertyChanged("IdDestino");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoDestino TipoDestino {
            get {
                return this.tipoDestinoField;
            }
            set {
                this.tipoDestinoField = value;
                this.RaisePropertyChanged("TipoDestino");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NombreDestino {
            get {
                return this.nombreDestinoField;
            }
            set {
                this.nombreDestinoField = value;
                this.RaisePropertyChanged("NombreDestino");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum TipoDestino {
        
        /// <comentarios/>
        Ciudad,
        
        /// <comentarios/>
        Provincia,
        
        /// <comentarios/>
        Region,
        
        /// <comentarios/>
        NoEspecificado,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoAlojamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idAlojamientoField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string descripcion2Field;
        
        private string direccionField;
        
        private string telefonoField;
        
        private InfoDestino destinoField;
        
        private TipoAlojamiento tipoField;
        
        private CategoriaAlojamiento categoriaField;
        
        private string politicasCancelacionField;
        
        private string fotoAlojamientoUrlField;
        
        private string fotoAlojamientoDescripcionField;
        
        private string[] fotoUrlListaField;
        
        private string[] fotoDescripcionListaField;
        
        private string[] amenidadesField;
        
        private RegimenAlojamiento regimenField;
        
        private bool bajoPeticionField;
        
        private Moneda monedaField;
        
        private InfoUnidad[] unidadesField;
        
        private System.Nullable<float> latitudField;
        
        private System.Nullable<float> longitudField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Descripcion2 {
            get {
                return this.descripcion2Field;
            }
            set {
                this.descripcion2Field = value;
                this.RaisePropertyChanged("Descripcion2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public InfoDestino Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TipoAlojamiento Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public CategoriaAlojamiento Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("Categoria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PoliticasCancelacion {
            get {
                return this.politicasCancelacionField;
            }
            set {
                this.politicasCancelacionField = value;
                this.RaisePropertyChanged("PoliticasCancelacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FotoAlojamientoUrl {
            get {
                return this.fotoAlojamientoUrlField;
            }
            set {
                this.fotoAlojamientoUrlField = value;
                this.RaisePropertyChanged("FotoAlojamientoUrl");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FotoAlojamientoDescripcion {
            get {
                return this.fotoAlojamientoDescripcionField;
            }
            set {
                this.fotoAlojamientoDescripcionField = value;
                this.RaisePropertyChanged("FotoAlojamientoDescripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public string[] FotoUrlLista {
            get {
                return this.fotoUrlListaField;
            }
            set {
                this.fotoUrlListaField = value;
                this.RaisePropertyChanged("FotoUrlLista");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public string[] FotoDescripcionLista {
            get {
                return this.fotoDescripcionListaField;
            }
            set {
                this.fotoDescripcionListaField = value;
                this.RaisePropertyChanged("FotoDescripcionLista");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public string[] Amenidades {
            get {
                return this.amenidadesField;
            }
            set {
                this.amenidadesField = value;
                this.RaisePropertyChanged("Amenidades");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public RegimenAlojamiento Regimen {
            get {
                return this.regimenField;
            }
            set {
                this.regimenField = value;
                this.RaisePropertyChanged("Regimen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool BajoPeticion {
            get {
                return this.bajoPeticionField;
            }
            set {
                this.bajoPeticionField = value;
                this.RaisePropertyChanged("BajoPeticion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public Moneda Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public InfoUnidad[] Unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("Unidades");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<float> Latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("Latitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<float> Longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("Longitud");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum TipoAlojamiento {
        
        /// <comentarios/>
        SinTipoAlojamiento,
        
        /// <comentarios/>
        ApartHotel,
        
        /// <comentarios/>
        BandB,
        
        /// <comentarios/>
        Bodega,
        
        /// <comentarios/>
        Bungalows,
        
        /// <comentarios/>
        Cabanyas,
        
        /// <comentarios/>
        ComplejoTuristico,
        
        /// <comentarios/>
        EstanciaRanches,
        
        /// <comentarios/>
        Hospedaje,
        
        /// <comentarios/>
        Hostal,
        
        /// <comentarios/>
        Hosteria,
        
        /// <comentarios/>
        Hotel,
        
        /// <comentarios/>
        HotelBoutique,
        
        /// <comentarios/>
        HotelSpa,
        
        /// <comentarios/>
        Lodge,
        
        /// <comentarios/>
        Motel,
        
        /// <comentarios/>
        Parador,
        
        /// <comentarios/>
        Posada,
        
        /// <comentarios/>
        Resort,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum CategoriaAlojamiento {
        
        /// <comentarios/>
        OtraCategoria,
        
        /// <comentarios/>
        SinCategoria,
        
        /// <comentarios/>
        Estrellas1,
        
        /// <comentarios/>
        Estrellas2,
        
        /// <comentarios/>
        Estrellas3,
        
        /// <comentarios/>
        Estrellas4,
        
        /// <comentarios/>
        Estrellas5,
        
        /// <comentarios/>
        Estrellas6,
        
        /// <comentarios/>
        Estrellas7,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum RegimenAlojamiento {
        
        /// <comentarios/>
        NoInformado,
        
        /// <comentarios/>
        Desayuno,
        
        /// <comentarios/>
        MediaPension,
        
        /// <comentarios/>
        PensionCompleta,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum Moneda {
        
        /// <comentarios/>
        ARS,
        
        /// <comentarios/>
        USD,
        
        /// <comentarios/>
        EUR,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoUnidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idUnidadField;
        
        private System.DateTime fechaField;
        
        private string nombreUnidadField;
        
        private int personasField;
        
        private int camasField;
        
        private int disponiblesField;
        
        private decimal montoPorUnidadField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdUnidad {
            get {
                return this.idUnidadField;
            }
            set {
                this.idUnidadField = value;
                this.RaisePropertyChanged("IdUnidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NombreUnidad {
            get {
                return this.nombreUnidadField;
            }
            set {
                this.nombreUnidadField = value;
                this.RaisePropertyChanged("NombreUnidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Personas {
            get {
                return this.personasField;
            }
            set {
                this.personasField = value;
                this.RaisePropertyChanged("Personas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Camas {
            get {
                return this.camasField;
            }
            set {
                this.camasField = value;
                this.RaisePropertyChanged("Camas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Disponibles {
            get {
                return this.disponiblesField;
            }
            set {
                this.disponiblesField = value;
                this.RaisePropertyChanged("Disponibles");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal MontoPorUnidad {
            get {
                return this.montoPorUnidadField;
            }
            set {
                this.montoPorUnidadField = value;
                this.RaisePropertyChanged("MontoPorUnidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class DetalleReserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int cantidadField;
        
        private System.DateTime fechaInicialField;
        
        private System.DateTime fechaFinalField;
        
        private int diasField;
        
        private decimal porUnidadField;
        
        private decimal subtotalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime FechaInicial {
            get {
                return this.fechaInicialField;
            }
            set {
                this.fechaInicialField = value;
                this.RaisePropertyChanged("FechaInicial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime FechaFinal {
            get {
                return this.fechaFinalField;
            }
            set {
                this.fechaFinalField = value;
                this.RaisePropertyChanged("FechaFinal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Dias {
            get {
                return this.diasField;
            }
            set {
                this.diasField = value;
                this.RaisePropertyChanged("Dias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal PorUnidad {
            get {
                return this.porUnidadField;
            }
            set {
                this.porUnidadField = value;
                this.RaisePropertyChanged("PorUnidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("Subtotal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoAlojamientoDisponible : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoDestino destinoField;
        
        private System.Nullable<TipoAlojamiento> tipoAlojamientoField;
        
        private System.Nullable<System.Guid> idAlojamientoField;
        
        private string nombreField;
        
        private System.Nullable<Moneda> monedaField;
        
        private System.Nullable<decimal> tarifa1Field;
        
        private System.Nullable<decimal> tarifa2Field;
        
        private System.Nullable<decimal> tarifa3Field;
        
        private System.Nullable<decimal> tarifa4Field;
        
        private System.Nullable<decimal> tarifa5Field;
        
        private System.Nullable<decimal> tarifa6Field;
        
        private System.Nullable<int> cupo1Field;
        
        private System.Nullable<int> cupo2Field;
        
        private System.Nullable<int> cupo3Field;
        
        private System.Nullable<int> cupo4Field;
        
        private System.Nullable<int> cupo5Field;
        
        private System.Nullable<int> cupo6Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfoDestino Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<TipoAlojamiento> TipoAlojamiento {
            get {
                return this.tipoAlojamientoField;
            }
            set {
                this.tipoAlojamientoField = value;
                this.RaisePropertyChanged("TipoAlojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.Guid> IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<Moneda> Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> Tarifa1 {
            get {
                return this.tarifa1Field;
            }
            set {
                this.tarifa1Field = value;
                this.RaisePropertyChanged("Tarifa1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> Tarifa2 {
            get {
                return this.tarifa2Field;
            }
            set {
                this.tarifa2Field = value;
                this.RaisePropertyChanged("Tarifa2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> Tarifa3 {
            get {
                return this.tarifa3Field;
            }
            set {
                this.tarifa3Field = value;
                this.RaisePropertyChanged("Tarifa3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> Tarifa4 {
            get {
                return this.tarifa4Field;
            }
            set {
                this.tarifa4Field = value;
                this.RaisePropertyChanged("Tarifa4");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> Tarifa5 {
            get {
                return this.tarifa5Field;
            }
            set {
                this.tarifa5Field = value;
                this.RaisePropertyChanged("Tarifa5");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> Tarifa6 {
            get {
                return this.tarifa6Field;
            }
            set {
                this.tarifa6Field = value;
                this.RaisePropertyChanged("Tarifa6");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> Cupo1 {
            get {
                return this.cupo1Field;
            }
            set {
                this.cupo1Field = value;
                this.RaisePropertyChanged("Cupo1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> Cupo2 {
            get {
                return this.cupo2Field;
            }
            set {
                this.cupo2Field = value;
                this.RaisePropertyChanged("Cupo2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> Cupo3 {
            get {
                return this.cupo3Field;
            }
            set {
                this.cupo3Field = value;
                this.RaisePropertyChanged("Cupo3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> Cupo4 {
            get {
                return this.cupo4Field;
            }
            set {
                this.cupo4Field = value;
                this.RaisePropertyChanged("Cupo4");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> Cupo5 {
            get {
                return this.cupo5Field;
            }
            set {
                this.cupo5Field = value;
                this.RaisePropertyChanged("Cupo5");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> Cupo6 {
            get {
                return this.cupo6Field;
            }
            set {
                this.cupo6Field = value;
                this.RaisePropertyChanged("Cupo6");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaBuscarAlojamientosEInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaConsultarReservaAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaCancelarReservaAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaReservarAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaInfoAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaInfoCuposAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaBuscarAlojamientos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaBuscarDestinos))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public abstract partial class RespuestaBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EstadoRespuesta estadoField;
        
        private string mensajeEstadoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EstadoRespuesta Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MensajeEstado {
            get {
                return this.mensajeEstadoField;
            }
            set {
                this.mensajeEstadoField = value;
                this.RaisePropertyChanged("MensajeEstado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum EstadoRespuesta {
        
        /// <comentarios/>
        Ok,
        
        /// <comentarios/>
        NoEncontrado,
        
        /// <comentarios/>
        NoHayCupo,
        
        /// <comentarios/>
        OperacionFallida,
        
        /// <comentarios/>
        ErrorParametro,
        
        /// <comentarios/>
        ErrorInterno,
        
        /// <comentarios/>
        CredencialesNoValidas,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaBuscarAlojamientosEInfo : RespuestaBase {
        
        private InfoAlojamientoDisponibleCompleta[] alojamientosDisponiblesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public InfoAlojamientoDisponibleCompleta[] AlojamientosDisponibles {
            get {
                return this.alojamientosDisponiblesField;
            }
            set {
                this.alojamientosDisponiblesField = value;
                this.RaisePropertyChanged("AlojamientosDisponibles");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaConsultarReservaAlojamiento : RespuestaBase {
        
        private InfoPasajero pasajeroField;
        
        private InfoAlojamiento alojamientoField;
        
        private System.Nullable<EstadoReserva> estadoReservaField;
        
        private System.Nullable<Moneda> monedaField;
        
        private System.Nullable<decimal> totalField;
        
        private DetalleReserva[] detallesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfoPasajero Pasajero {
            get {
                return this.pasajeroField;
            }
            set {
                this.pasajeroField = value;
                this.RaisePropertyChanged("Pasajero");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InfoAlojamiento Alojamiento {
            get {
                return this.alojamientoField;
            }
            set {
                this.alojamientoField = value;
                this.RaisePropertyChanged("Alojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<EstadoReserva> EstadoReserva {
            get {
                return this.estadoReservaField;
            }
            set {
                this.estadoReservaField = value;
                this.RaisePropertyChanged("EstadoReserva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<Moneda> Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public DetalleReserva[] Detalles {
            get {
                return this.detallesField;
            }
            set {
                this.detallesField = value;
                this.RaisePropertyChanged("Detalles");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoPasajero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string apellidoField;
        
        private Sexo sexoField;
        
        private System.Nullable<System.DateTime> fechaNacimientoField;
        
        private TipoDocumento tipoDocumentoField;
        
        private string documentoField;
        
        private string direccionField;
        
        private string ciudadField;
        
        private string paisField;
        
        private string telefonoField;
        
        private string emailField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Sexo Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("FechaNacimiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TipoDocumento TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("TipoDocumento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("Ciudad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("Pais");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum Sexo {
        
        /// <comentarios/>
        Masculino,
        
        /// <comentarios/>
        Femenino,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum TipoDocumento {
        
        /// <comentarios/>
        DNI,
        
        /// <comentarios/>
        CUIT,
        
        /// <comentarios/>
        Pasaporte,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum EstadoReserva {
        
        /// <comentarios/>
        ReservaAConstatar,
        
        /// <comentarios/>
        ReservaEfectiva,
        
        /// <comentarios/>
        ReservaCancelada,
        
        /// <comentarios/>
        ReservaRechazada,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaCancelarReservaAlojamiento : RespuestaBase {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaReservarAlojamiento : RespuestaBase {
        
        private System.Nullable<System.Guid> idReservaField;
        
        private System.Nullable<int> codigoReservaField;
        
        private System.Nullable<Moneda> monedaField;
        
        private System.Nullable<decimal> totalField;
        
        private System.Nullable<System.DateTime> vencimientoReservaField;
        
        private DetalleReserva[] detallesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.Guid> IdReserva {
            get {
                return this.idReservaField;
            }
            set {
                this.idReservaField = value;
                this.RaisePropertyChanged("IdReserva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> CodigoReserva {
            get {
                return this.codigoReservaField;
            }
            set {
                this.codigoReservaField = value;
                this.RaisePropertyChanged("CodigoReserva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<Moneda> Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> VencimientoReserva {
            get {
                return this.vencimientoReservaField;
            }
            set {
                this.vencimientoReservaField = value;
                this.RaisePropertyChanged("VencimientoReserva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public DetalleReserva[] Detalles {
            get {
                return this.detallesField;
            }
            set {
                this.detallesField = value;
                this.RaisePropertyChanged("Detalles");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaInfoCuposAlojamiento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaInfoAlojamiento : RespuestaBase {
        
        private InfoAlojamiento alojamientoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfoAlojamiento Alojamiento {
            get {
                return this.alojamientoField;
            }
            set {
                this.alojamientoField = value;
                this.RaisePropertyChanged("Alojamiento");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaInfoCuposAlojamiento : RespuestaInfoAlojamiento {
        
        private Moneda monedaField;
        
        private InfoUnidad[] unidadesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Moneda Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public InfoUnidad[] Unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("Unidades");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaBuscarAlojamientos : RespuestaBase {
        
        private InfoAlojamientoDisponible[] alojamientosDisponiblesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public InfoAlojamientoDisponible[] AlojamientosDisponibles {
            get {
                return this.alojamientosDisponiblesField;
            }
            set {
                this.alojamientosDisponiblesField = value;
                this.RaisePropertyChanged("AlojamientosDisponibles");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaBuscarDestinos : RespuestaBase {
        
        private InfoDestino[] destinosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public InfoDestino[] Destinos {
            get {
                return this.destinosField;
            }
            set {
                this.destinosField = value;
                this.RaisePropertyChanged("Destinos");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class DetalleUnidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idUnidadField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private int cantidadField;
        
        private InfoPasajero[] pasajerosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdUnidad {
            get {
                return this.idUnidadField;
            }
            set {
                this.idUnidadField = value;
                this.RaisePropertyChanged("IdUnidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("FechaInicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("FechaFin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public InfoPasajero[] Pasajeros {
            get {
                return this.pasajerosField;
            }
            set {
                this.pasajerosField = value;
                this.RaisePropertyChanged("Pasajeros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionConsultarReservaAlojamiento : PeticionBase {
        
        private System.Guid idReservaField;
        
        private int codigoReservaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdReserva {
            get {
                return this.idReservaField;
            }
            set {
                this.idReservaField = value;
                this.RaisePropertyChanged("IdReserva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CodigoReserva {
            get {
                return this.codigoReservaField;
            }
            set {
                this.codigoReservaField = value;
                this.RaisePropertyChanged("CodigoReserva");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionCancelarReservaAlojamiento : PeticionBase {
        
        private System.Guid idReservaField;
        
        private int codigoReservaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdReserva {
            get {
                return this.idReservaField;
            }
            set {
                this.idReservaField = value;
                this.RaisePropertyChanged("IdReserva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CodigoReserva {
            get {
                return this.codigoReservaField;
            }
            set {
                this.codigoReservaField = value;
                this.RaisePropertyChanged("CodigoReserva");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionReservarAlojamiento : PeticionBase {
        
        private System.Guid idAlojamientoField;
        
        private System.Guid idFormaPagoField;
        
        private InfoPasajero titularField;
        
        private DetalleUnidad[] unidadesField;
        
        private string nacionalidadField;
        
        private string observacionesField;
        
        private EstadoReserva estadoReservaField;
        
        private bool incurreGastosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid IdFormaPago {
            get {
                return this.idFormaPagoField;
            }
            set {
                this.idFormaPagoField = value;
                this.RaisePropertyChanged("IdFormaPago");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public InfoPasajero Titular {
            get {
                return this.titularField;
            }
            set {
                this.titularField = value;
                this.RaisePropertyChanged("Titular");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public DetalleUnidad[] Unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("Unidades");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("Nacionalidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("Observaciones");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public EstadoReserva EstadoReserva {
            get {
                return this.estadoReservaField;
            }
            set {
                this.estadoReservaField = value;
                this.RaisePropertyChanged("EstadoReserva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IncurreGastos {
            get {
                return this.incurreGastosField;
            }
            set {
                this.incurreGastosField = value;
                this.RaisePropertyChanged("IncurreGastos");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionInfoCuposAlojamiento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionInfoAlojamiento : PeticionBase {
        
        private System.Guid idAlojamientoField;
        
        private System.DateTime fechaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionInfoCuposAlojamiento : PeticionInfoAlojamiento {
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private string nacionalidadField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("FechaInicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("FechaFin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("Nacionalidad");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionBuscarAlojamientos : PeticionBase {
        
        private System.Guid idDestinoField;
        
        private TipoDestino tipoDestinoField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private System.Nullable<TipoAlojamiento> tipoAlojamientoField;
        
        private System.Nullable<int> habitacion1Field;
        
        private System.Nullable<int> habitacion2Field;
        
        private System.Nullable<int> habitacion3Field;
        
        private System.Nullable<int> habitacion4Field;
        
        private System.Nullable<int> habitacion5Field;
        
        private System.Nullable<int> habitacion6Field;
        
        private System.Nullable<OrdenAlojamientos> ordenField;
        
        private string nacionalidadField;
        
        private string nombreAlojamientoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdDestino {
            get {
                return this.idDestinoField;
            }
            set {
                this.idDestinoField = value;
                this.RaisePropertyChanged("IdDestino");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoDestino TipoDestino {
            get {
                return this.tipoDestinoField;
            }
            set {
                this.tipoDestinoField = value;
                this.RaisePropertyChanged("TipoDestino");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("FechaInicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("FechaFin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<TipoAlojamiento> TipoAlojamiento {
            get {
                return this.tipoAlojamientoField;
            }
            set {
                this.tipoAlojamientoField = value;
                this.RaisePropertyChanged("TipoAlojamiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> Habitacion1 {
            get {
                return this.habitacion1Field;
            }
            set {
                this.habitacion1Field = value;
                this.RaisePropertyChanged("Habitacion1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> Habitacion2 {
            get {
                return this.habitacion2Field;
            }
            set {
                this.habitacion2Field = value;
                this.RaisePropertyChanged("Habitacion2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> Habitacion3 {
            get {
                return this.habitacion3Field;
            }
            set {
                this.habitacion3Field = value;
                this.RaisePropertyChanged("Habitacion3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> Habitacion4 {
            get {
                return this.habitacion4Field;
            }
            set {
                this.habitacion4Field = value;
                this.RaisePropertyChanged("Habitacion4");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> Habitacion5 {
            get {
                return this.habitacion5Field;
            }
            set {
                this.habitacion5Field = value;
                this.RaisePropertyChanged("Habitacion5");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> Habitacion6 {
            get {
                return this.habitacion6Field;
            }
            set {
                this.habitacion6Field = value;
                this.RaisePropertyChanged("Habitacion6");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<OrdenAlojamientos> Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("Nacionalidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NombreAlojamiento {
            get {
                return this.nombreAlojamientoField;
            }
            set {
                this.nombreAlojamientoField = value;
                this.RaisePropertyChanged("NombreAlojamiento");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum OrdenAlojamientos {
        
        /// <comentarios/>
        PorNombre,
        
        /// <comentarios/>
        PorPrecio,
        
        /// <comentarios/>
        PorCategoria,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelesSoapSoapChannel : Ineltur.WebService.NationalService.HotelesSoapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelesSoapSoapClient : System.ServiceModel.ClientBase<Ineltur.WebService.NationalService.HotelesSoapSoap>, Ineltur.WebService.NationalService.HotelesSoapSoap {
        
        public HotelesSoapSoapClient() {
        }
        
        public HotelesSoapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelesSoapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelesSoapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelesSoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ineltur.WebService.NationalService.RespuestaBuscarDestinos BuscarDestinos(Ineltur.WebService.NationalService.PeticionBuscarDestinos peticion) {
            return base.Channel.BuscarDestinos(peticion);
        }
        
        public Ineltur.WebService.NationalService.RespuestaBuscarAlojamientos BuscarAlojamientos(Ineltur.WebService.NationalService.PeticionBuscarAlojamientos peticion) {
            return base.Channel.BuscarAlojamientos(peticion);
        }
        
        public Ineltur.WebService.NationalService.RespuestaInfoAlojamiento InfoAlojamiento(Ineltur.WebService.NationalService.PeticionInfoAlojamiento peticion) {
            return base.Channel.InfoAlojamiento(peticion);
        }
        
        public Ineltur.WebService.NationalService.RespuestaInfoCuposAlojamiento InfoCuposAlojamiento(Ineltur.WebService.NationalService.PeticionInfoCuposAlojamiento peticion) {
            return base.Channel.InfoCuposAlojamiento(peticion);
        }
        
        public Ineltur.WebService.NationalService.RespuestaReservarAlojamiento ReservarAlojamiento(Ineltur.WebService.NationalService.PeticionReservarAlojamiento peticion) {
            return base.Channel.ReservarAlojamiento(peticion);
        }
        
        public Ineltur.WebService.NationalService.RespuestaCancelarReservaAlojamiento CancelarReservaAlojamiento(Ineltur.WebService.NationalService.PeticionCancelarReservaAlojamiento peticion) {
            return base.Channel.CancelarReservaAlojamiento(peticion);
        }
        
        public Ineltur.WebService.NationalService.RespuestaConsultarReservaAlojamiento ConsultarReservaAlojamiento(Ineltur.WebService.NationalService.PeticionConsultarReservaAlojamiento peticion) {
            return base.Channel.ConsultarReservaAlojamiento(peticion);
        }
        
        public Ineltur.WebService.NationalService.RespuestaBuscarAlojamientosEInfo BuscarAlojamientosEInfo(Ineltur.WebService.NationalService.PeticionBuscarAlojamientos peticion) {
            return base.Channel.BuscarAlojamientosEInfo(peticion);
        }
    }
}
