//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckArgentina.LocalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ineltur.com/", ConfigurationName="LocalService.ServiciosSoapSoap")]
    public interface ServiciosSoapSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        CheckArgentina.LocalService.RespuestaLogin Login(CheckArgentina.LocalService.PeticionLogin peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<CheckArgentina.LocalService.RespuestaLogin> LoginAsync(CheckArgentina.LocalService.PeticionLogin peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/BuscarMisReservas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        CheckArgentina.LocalService.RespuestaBuscarMisReservas BuscarMisReservas(CheckArgentina.LocalService.PeticionBuscarMisReservas peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/BuscarMisReservas", ReplyAction="*")]
        System.Threading.Tasks.Task<CheckArgentina.LocalService.RespuestaBuscarMisReservas> BuscarMisReservasAsync(CheckArgentina.LocalService.PeticionBuscarMisReservas peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/BuscarPreciosSemanalesHotel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        CheckArgentina.LocalService.RespuestaInfoCuposSemanalesAlojamiento BuscarPreciosSemanalesHotel(CheckArgentina.LocalService.PeticionInfoAlojamiento peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/BuscarPreciosSemanalesHotel", ReplyAction="*")]
        System.Threading.Tasks.Task<CheckArgentina.LocalService.RespuestaInfoCuposSemanalesAlojamiento> BuscarPreciosSemanalesHotelAsync(CheckArgentina.LocalService.PeticionInfoAlojamiento peticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/SearchHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionBase))]
        CheckArgentina.LocalService.RespuestaBuscarAlojamientosEInfo SearchHotels(CheckArgentina.LocalService.PeticionBuscarAlojamientos petition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ineltur.com/SearchHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<CheckArgentina.LocalService.RespuestaBuscarAlojamientosEInfo> SearchHotelsAsync(CheckArgentina.LocalService.PeticionBuscarAlojamientos petition);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionLogin : PeticionBase {
        
        private string userField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionBuscarAlojamientos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionInfoAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionBuscarMisReservas))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionLogin))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public abstract partial class PeticionBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string claveField;
        
        private string idiomaDeseadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdiomaDeseado {
            get {
                return this.idiomaDeseadoField;
            }
            set {
                this.idiomaDeseadoField = value;
                this.RaisePropertyChanged("IdiomaDeseado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoUnidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idUnidadField;
        
        private System.DateTime fechaField;
        
        private string nombreUnidadField;
        
        private int personasField;
        
        private int camasField;
        
        private int disponiblesField;
        
        private decimal montoPorUnidadField;
        
        private int desayunoField;
        
        private int tarifaField;
        
        private bool tienePromocionNxMField;
        
        private System.Nullable<int> diasACobrarField;
        
        private bool tienePromocionMinimoMaximoField;
        
        private System.Nullable<int> minimoDiasField;
        
        private System.Nullable<int> maximoDiasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdUnidad {
            get {
                return this.idUnidadField;
            }
            set {
                this.idUnidadField = value;
                this.RaisePropertyChanged("IdUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NombreUnidad {
            get {
                return this.nombreUnidadField;
            }
            set {
                this.nombreUnidadField = value;
                this.RaisePropertyChanged("NombreUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Personas {
            get {
                return this.personasField;
            }
            set {
                this.personasField = value;
                this.RaisePropertyChanged("Personas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Camas {
            get {
                return this.camasField;
            }
            set {
                this.camasField = value;
                this.RaisePropertyChanged("Camas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Disponibles {
            get {
                return this.disponiblesField;
            }
            set {
                this.disponiblesField = value;
                this.RaisePropertyChanged("Disponibles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal MontoPorUnidad {
            get {
                return this.montoPorUnidadField;
            }
            set {
                this.montoPorUnidadField = value;
                this.RaisePropertyChanged("MontoPorUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Desayuno {
            get {
                return this.desayunoField;
            }
            set {
                this.desayunoField = value;
                this.RaisePropertyChanged("Desayuno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
                this.RaisePropertyChanged("Tarifa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool TienePromocionNxM {
            get {
                return this.tienePromocionNxMField;
            }
            set {
                this.tienePromocionNxMField = value;
                this.RaisePropertyChanged("TienePromocionNxM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> DiasACobrar {
            get {
                return this.diasACobrarField;
            }
            set {
                this.diasACobrarField = value;
                this.RaisePropertyChanged("DiasACobrar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool TienePromocionMinimoMaximo {
            get {
                return this.tienePromocionMinimoMaximoField;
            }
            set {
                this.tienePromocionMinimoMaximoField = value;
                this.RaisePropertyChanged("TienePromocionMinimoMaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> MinimoDias {
            get {
                return this.minimoDiasField;
            }
            set {
                this.minimoDiasField = value;
                this.RaisePropertyChanged("MinimoDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> MaximoDias {
            get {
                return this.maximoDiasField;
            }
            set {
                this.maximoDiasField = value;
                this.RaisePropertyChanged("MaximoDias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoAlojamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idAlojamientoField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string descripcion2Field;
        
        private string direccionField;
        
        private string telefonoField;
        
        private InfoDestino destinoField;
        
        private TipoAlojamiento tipoField;
        
        private CategoriaAlojamiento categoriaField;
        
        private string politicasCancelacionField;
        
        private string fotoAlojamientoUrlField;
        
        private string fotoAlojamientoDescripcionField;
        
        private string[] fotoUrlListaField;
        
        private string[] fotoDescripcionListaField;
        
        private string[] amenidadesField;
        
        private RegimenAlojamiento regimenField;
        
        private bool bajoPeticionField;
        
        private Moneda monedaField;
        
        private InfoUnidad[] unidadesField;
        
        private System.Nullable<float> latitudField;
        
        private System.Nullable<float> longitudField;
        
        private bool tienePromocionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Descripcion2 {
            get {
                return this.descripcion2Field;
            }
            set {
                this.descripcion2Field = value;
                this.RaisePropertyChanged("Descripcion2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public InfoDestino Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TipoAlojamiento Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public CategoriaAlojamiento Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("Categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PoliticasCancelacion {
            get {
                return this.politicasCancelacionField;
            }
            set {
                this.politicasCancelacionField = value;
                this.RaisePropertyChanged("PoliticasCancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FotoAlojamientoUrl {
            get {
                return this.fotoAlojamientoUrlField;
            }
            set {
                this.fotoAlojamientoUrlField = value;
                this.RaisePropertyChanged("FotoAlojamientoUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FotoAlojamientoDescripcion {
            get {
                return this.fotoAlojamientoDescripcionField;
            }
            set {
                this.fotoAlojamientoDescripcionField = value;
                this.RaisePropertyChanged("FotoAlojamientoDescripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public string[] FotoUrlLista {
            get {
                return this.fotoUrlListaField;
            }
            set {
                this.fotoUrlListaField = value;
                this.RaisePropertyChanged("FotoUrlLista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public string[] FotoDescripcionLista {
            get {
                return this.fotoDescripcionListaField;
            }
            set {
                this.fotoDescripcionListaField = value;
                this.RaisePropertyChanged("FotoDescripcionLista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public string[] Amenidades {
            get {
                return this.amenidadesField;
            }
            set {
                this.amenidadesField = value;
                this.RaisePropertyChanged("Amenidades");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public RegimenAlojamiento Regimen {
            get {
                return this.regimenField;
            }
            set {
                this.regimenField = value;
                this.RaisePropertyChanged("Regimen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool BajoPeticion {
            get {
                return this.bajoPeticionField;
            }
            set {
                this.bajoPeticionField = value;
                this.RaisePropertyChanged("BajoPeticion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public Moneda Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public InfoUnidad[] Unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("Unidades");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<float> Latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("Latitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<float> Longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("Longitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool TienePromocion {
            get {
                return this.tienePromocionField;
            }
            set {
                this.tienePromocionField = value;
                this.RaisePropertyChanged("TienePromocion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoDestino : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idDestinoField;
        
        private TipoDestino tipoDestinoField;
        
        private string nombreDestinoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdDestino {
            get {
                return this.idDestinoField;
            }
            set {
                this.idDestinoField = value;
                this.RaisePropertyChanged("IdDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoDestino TipoDestino {
            get {
                return this.tipoDestinoField;
            }
            set {
                this.tipoDestinoField = value;
                this.RaisePropertyChanged("TipoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NombreDestino {
            get {
                return this.nombreDestinoField;
            }
            set {
                this.nombreDestinoField = value;
                this.RaisePropertyChanged("NombreDestino");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum TipoDestino {
        
        /// <remarks/>
        Ciudad,
        
        /// <remarks/>
        Provincia,
        
        /// <remarks/>
        Region,
        
        /// <remarks/>
        NoEspecificado,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum TipoAlojamiento {
        
        /// <remarks/>
        SinTipoAlojamiento,
        
        /// <remarks/>
        ApartHotel,
        
        /// <remarks/>
        BandB,
        
        /// <remarks/>
        Bodega,
        
        /// <remarks/>
        Bungalows,
        
        /// <remarks/>
        Cabanyas,
        
        /// <remarks/>
        ComplejoTuristico,
        
        /// <remarks/>
        EstanciaRanches,
        
        /// <remarks/>
        Hospedaje,
        
        /// <remarks/>
        Hostal,
        
        /// <remarks/>
        Hosteria,
        
        /// <remarks/>
        Hotel,
        
        /// <remarks/>
        HotelBoutique,
        
        /// <remarks/>
        HotelSpa,
        
        /// <remarks/>
        Lodge,
        
        /// <remarks/>
        Motel,
        
        /// <remarks/>
        Parador,
        
        /// <remarks/>
        Posada,
        
        /// <remarks/>
        Resort,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum CategoriaAlojamiento {
        
        /// <remarks/>
        OtraCategoria,
        
        /// <remarks/>
        SinCategoria,
        
        /// <remarks/>
        Estrellas1,
        
        /// <remarks/>
        Estrellas2,
        
        /// <remarks/>
        Estrellas3,
        
        /// <remarks/>
        Estrellas4,
        
        /// <remarks/>
        Estrellas5,
        
        /// <remarks/>
        Estrellas6,
        
        /// <remarks/>
        Estrellas7,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum RegimenAlojamiento {
        
        /// <remarks/>
        NoInformado,
        
        /// <remarks/>
        Desayuno,
        
        /// <remarks/>
        MediaPension,
        
        /// <remarks/>
        PensionCompleta,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum Moneda {
        
        /// <remarks/>
        ARS,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        EUR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoAlojamientoDisponibleCompleta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoDestino destinoField;
        
        private InfoAlojamiento alojamientoField;
        
        private System.Nullable<TipoAlojamiento> tipoAlojamientoField;
        
        private System.Nullable<System.Guid> idAlojamientoField;
        
        private string nombreField;
        
        private System.Nullable<Moneda> monedaField;
        
        private System.Nullable<float> montoUnidadMasBarataField;
        
        private System.Nullable<decimal> tarifa1Field;
        
        private System.Nullable<decimal> tarifa2Field;
        
        private System.Nullable<decimal> tarifa3Field;
        
        private System.Nullable<decimal> tarifa4Field;
        
        private System.Nullable<decimal> tarifa5Field;
        
        private System.Nullable<decimal> tarifa6Field;
        
        private System.Nullable<int> cupo1Field;
        
        private System.Nullable<int> cupo2Field;
        
        private System.Nullable<int> cupo3Field;
        
        private System.Nullable<int> cupo4Field;
        
        private System.Nullable<int> cupo5Field;
        
        private System.Nullable<int> cupo6Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfoDestino Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InfoAlojamiento Alojamiento {
            get {
                return this.alojamientoField;
            }
            set {
                this.alojamientoField = value;
                this.RaisePropertyChanged("Alojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<TipoAlojamiento> TipoAlojamiento {
            get {
                return this.tipoAlojamientoField;
            }
            set {
                this.tipoAlojamientoField = value;
                this.RaisePropertyChanged("TipoAlojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.Guid> IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<Moneda> Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<float> MontoUnidadMasBarata {
            get {
                return this.montoUnidadMasBarataField;
            }
            set {
                this.montoUnidadMasBarataField = value;
                this.RaisePropertyChanged("MontoUnidadMasBarata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> Tarifa1 {
            get {
                return this.tarifa1Field;
            }
            set {
                this.tarifa1Field = value;
                this.RaisePropertyChanged("Tarifa1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> Tarifa2 {
            get {
                return this.tarifa2Field;
            }
            set {
                this.tarifa2Field = value;
                this.RaisePropertyChanged("Tarifa2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> Tarifa3 {
            get {
                return this.tarifa3Field;
            }
            set {
                this.tarifa3Field = value;
                this.RaisePropertyChanged("Tarifa3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> Tarifa4 {
            get {
                return this.tarifa4Field;
            }
            set {
                this.tarifa4Field = value;
                this.RaisePropertyChanged("Tarifa4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> Tarifa5 {
            get {
                return this.tarifa5Field;
            }
            set {
                this.tarifa5Field = value;
                this.RaisePropertyChanged("Tarifa5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> Tarifa6 {
            get {
                return this.tarifa6Field;
            }
            set {
                this.tarifa6Field = value;
                this.RaisePropertyChanged("Tarifa6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> Cupo1 {
            get {
                return this.cupo1Field;
            }
            set {
                this.cupo1Field = value;
                this.RaisePropertyChanged("Cupo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> Cupo2 {
            get {
                return this.cupo2Field;
            }
            set {
                this.cupo2Field = value;
                this.RaisePropertyChanged("Cupo2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> Cupo3 {
            get {
                return this.cupo3Field;
            }
            set {
                this.cupo3Field = value;
                this.RaisePropertyChanged("Cupo3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> Cupo4 {
            get {
                return this.cupo4Field;
            }
            set {
                this.cupo4Field = value;
                this.RaisePropertyChanged("Cupo4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> Cupo5 {
            get {
                return this.cupo5Field;
            }
            set {
                this.cupo5Field = value;
                this.RaisePropertyChanged("Cupo5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<int> Cupo6 {
            get {
                return this.cupo6Field;
            }
            set {
                this.cupo6Field = value;
                this.RaisePropertyChanged("Cupo6");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class CupoUnidades : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool bloaqueadoPorPromoField;
        
        private int cupomaximoField;
        
        private int cupoReservadoField;
        
        private System.DateTime fechaField;
        
        private System.DateTime fecha_AltaField;
        
        private System.Guid idCupoUnidadField;
        
        private System.Guid idUnidadAlojField;
        
        private System.Nullable<int> marcaTemporadaField;
        
        private decimal montoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("Activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool BloaqueadoPorPromo {
            get {
                return this.bloaqueadoPorPromoField;
            }
            set {
                this.bloaqueadoPorPromoField = value;
                this.RaisePropertyChanged("BloaqueadoPorPromo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Cupomaximo {
            get {
                return this.cupomaximoField;
            }
            set {
                this.cupomaximoField = value;
                this.RaisePropertyChanged("Cupomaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CupoReservado {
            get {
                return this.cupoReservadoField;
            }
            set {
                this.cupoReservadoField = value;
                this.RaisePropertyChanged("CupoReservado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime Fecha_Alta {
            get {
                return this.fecha_AltaField;
            }
            set {
                this.fecha_AltaField = value;
                this.RaisePropertyChanged("Fecha_Alta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Guid IdCupoUnidad {
            get {
                return this.idCupoUnidadField;
            }
            set {
                this.idCupoUnidadField = value;
                this.RaisePropertyChanged("IdCupoUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Guid IdUnidadAloj {
            get {
                return this.idUnidadAlojField;
            }
            set {
                this.idUnidadAlojField = value;
                this.RaisePropertyChanged("IdUnidadAloj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> MarcaTemporada {
            get {
                return this.marcaTemporadaField;
            }
            set {
                this.marcaTemporadaField = value;
                this.RaisePropertyChanged("MarcaTemporada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("Monto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoUnidadConCupos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idUnidadField;
        
        private System.DateTime fechaField;
        
        private string nombreUnidadField;
        
        private int personasField;
        
        private int camasField;
        
        private int disponiblesField;
        
        private decimal montoPorUnidadField;
        
        private string descripcionField;
        
        private CupoUnidades[] cuposField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdUnidad {
            get {
                return this.idUnidadField;
            }
            set {
                this.idUnidadField = value;
                this.RaisePropertyChanged("IdUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NombreUnidad {
            get {
                return this.nombreUnidadField;
            }
            set {
                this.nombreUnidadField = value;
                this.RaisePropertyChanged("NombreUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Personas {
            get {
                return this.personasField;
            }
            set {
                this.personasField = value;
                this.RaisePropertyChanged("Personas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Camas {
            get {
                return this.camasField;
            }
            set {
                this.camasField = value;
                this.RaisePropertyChanged("Camas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Disponibles {
            get {
                return this.disponiblesField;
            }
            set {
                this.disponiblesField = value;
                this.RaisePropertyChanged("Disponibles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal MontoPorUnidad {
            get {
                return this.montoPorUnidadField;
            }
            set {
                this.montoPorUnidadField = value;
                this.RaisePropertyChanged("MontoPorUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public CupoUnidades[] Cupos {
            get {
                return this.cuposField;
            }
            set {
                this.cuposField = value;
                this.RaisePropertyChanged("Cupos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoCuposAlojamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idAlojamientoField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private InfoUnidadConCupos[] unidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public InfoUnidadConCupos[] Unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("Unidades");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class InfoUnidadReservada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private System.Nullable<int> cantidadField;
        
        private string nombreHabitacionField;
        
        private float montoField;
        
        private System.Nullable<float> montoTotalField;
        
        private System.Guid idUnidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("FechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("FechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NombreHabitacion {
            get {
                return this.nombreHabitacionField;
            }
            set {
                this.nombreHabitacionField = value;
                this.RaisePropertyChanged("NombreHabitacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("Monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<float> MontoTotal {
            get {
                return this.montoTotalField;
            }
            set {
                this.montoTotalField = value;
                this.RaisePropertyChanged("MontoTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Guid IdUnidad {
            get {
                return this.idUnidadField;
            }
            set {
                this.idUnidadField = value;
                this.RaisePropertyChanged("IdUnidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class Reserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoReservaField;
        
        private string descripcionField;
        
        private System.Nullable<int> estadoPagoField;
        
        private int estadoReservaField;
        
        private System.DateTime fechaAltaField;
        
        private System.Nullable<System.DateTime> fechaVencimientoField;
        
        private System.Nullable<System.Guid> idAlojamientoField;
        
        private System.Nullable<System.Guid> idFormaDePagoField;
        
        private System.Guid idMonedaField;
        
        private System.Nullable<int> idPuField;
        
        private System.Guid idSitioOrigenField;
        
        private System.Guid idTipoFormaDePagoField;
        
        private System.Guid idTransaccionField;
        
        private System.Nullable<System.Guid> idUsuarioField;
        
        private System.Nullable<float> montoTotalConDescuentoField;
        
        private System.Nullable<float> montoTotalSinDescuentoField;
        
        private string nombreAlojamientoField;
        
        private string nombreFormaDePagoField;
        
        private string nombrePasajeroField;
        
        private int tipoTransaccionField;
        
        private InfoUnidadReservada[] unidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CodigoReserva {
            get {
                return this.codigoReservaField;
            }
            set {
                this.codigoReservaField = value;
                this.RaisePropertyChanged("CodigoReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> EstadoPago {
            get {
                return this.estadoPagoField;
            }
            set {
                this.estadoPagoField = value;
                this.RaisePropertyChanged("EstadoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int EstadoReserva {
            get {
                return this.estadoReservaField;
            }
            set {
                this.estadoReservaField = value;
                this.RaisePropertyChanged("EstadoReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime FechaAlta {
            get {
                return this.fechaAltaField;
            }
            set {
                this.fechaAltaField = value;
                this.RaisePropertyChanged("FechaAlta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> FechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("FechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.Guid> IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.Guid> IdFormaDePago {
            get {
                return this.idFormaDePagoField;
            }
            set {
                this.idFormaDePagoField = value;
                this.RaisePropertyChanged("IdFormaDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Guid IdMoneda {
            get {
                return this.idMonedaField;
            }
            set {
                this.idMonedaField = value;
                this.RaisePropertyChanged("IdMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> IdPu {
            get {
                return this.idPuField;
            }
            set {
                this.idPuField = value;
                this.RaisePropertyChanged("IdPu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.Guid IdSitioOrigen {
            get {
                return this.idSitioOrigenField;
            }
            set {
                this.idSitioOrigenField = value;
                this.RaisePropertyChanged("IdSitioOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.Guid IdTipoFormaDePago {
            get {
                return this.idTipoFormaDePagoField;
            }
            set {
                this.idTipoFormaDePagoField = value;
                this.RaisePropertyChanged("IdTipoFormaDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.Guid IdTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("IdTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.Guid> IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<float> MontoTotalConDescuento {
            get {
                return this.montoTotalConDescuentoField;
            }
            set {
                this.montoTotalConDescuentoField = value;
                this.RaisePropertyChanged("MontoTotalConDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<float> MontoTotalSinDescuento {
            get {
                return this.montoTotalSinDescuentoField;
            }
            set {
                this.montoTotalSinDescuentoField = value;
                this.RaisePropertyChanged("MontoTotalSinDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string NombreAlojamiento {
            get {
                return this.nombreAlojamientoField;
            }
            set {
                this.nombreAlojamientoField = value;
                this.RaisePropertyChanged("NombreAlojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NombreFormaDePago {
            get {
                return this.nombreFormaDePagoField;
            }
            set {
                this.nombreFormaDePagoField = value;
                this.RaisePropertyChanged("NombreFormaDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string NombrePasajero {
            get {
                return this.nombrePasajeroField;
            }
            set {
                this.nombrePasajeroField = value;
                this.RaisePropertyChanged("NombrePasajero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int TipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                this.tipoTransaccionField = value;
                this.RaisePropertyChanged("TipoTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public InfoUnidadReservada[] Unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("Unidades");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaBuscarAlojamientosEInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaInfoCuposSemanalesAlojamiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaBuscarMisReservas))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaLogin))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public abstract partial class RespuestaBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EstadoRespuesta estadoField;
        
        private string mensajeEstadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EstadoRespuesta Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MensajeEstado {
            get {
                return this.mensajeEstadoField;
            }
            set {
                this.mensajeEstadoField = value;
                this.RaisePropertyChanged("MensajeEstado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum EstadoRespuesta {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        NoEncontrado,
        
        /// <remarks/>
        NoHayCupo,
        
        /// <remarks/>
        OperacionFallida,
        
        /// <remarks/>
        ErrorParametro,
        
        /// <remarks/>
        ErrorInterno,
        
        /// <remarks/>
        CredencialesNoValidas,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaBuscarAlojamientosEInfo : RespuestaBase {
        
        private InfoAlojamientoDisponibleCompleta[] alojamientosDisponiblesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public InfoAlojamientoDisponibleCompleta[] AlojamientosDisponibles {
            get {
                return this.alojamientosDisponiblesField;
            }
            set {
                this.alojamientosDisponiblesField = value;
                this.RaisePropertyChanged("AlojamientosDisponibles");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaInfoCuposSemanalesAlojamiento : RespuestaBase {
        
        private InfoCuposAlojamiento alojamientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfoCuposAlojamiento Alojamiento {
            get {
                return this.alojamientoField;
            }
            set {
                this.alojamientoField = value;
                this.RaisePropertyChanged("Alojamiento");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaBuscarMisReservas : RespuestaBase {
        
        private Reserva[] misReservasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Reserva[] MisReservas {
            get {
                return this.misReservasField;
            }
            set {
                this.misReservasField = value;
                this.RaisePropertyChanged("MisReservas");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class RespuestaLogin : RespuestaBase {
        
        private string userField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string uIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
                this.RaisePropertyChanged("UID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionBuscarAlojamientos : PeticionBase {
        
        private System.Guid idDestinoField;
        
        private TipoDestino tipoDestinoField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private System.Nullable<TipoAlojamiento> tipoAlojamientoField;
        
        private System.Nullable<int> habitacion1Field;
        
        private System.Nullable<int> habitacion2Field;
        
        private System.Nullable<int> habitacion3Field;
        
        private System.Nullable<int> habitacion4Field;
        
        private System.Nullable<int> habitacion5Field;
        
        private System.Nullable<int> habitacion6Field;
        
        private System.Nullable<OrdenAlojamientos> ordenField;
        
        private string nacionalidadField;
        
        private string nombreAlojamientoField;
        
        private int desayunoField;
        
        private int tarifaReembolsableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdDestino {
            get {
                return this.idDestinoField;
            }
            set {
                this.idDestinoField = value;
                this.RaisePropertyChanged("IdDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoDestino TipoDestino {
            get {
                return this.tipoDestinoField;
            }
            set {
                this.tipoDestinoField = value;
                this.RaisePropertyChanged("TipoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("FechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("FechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<TipoAlojamiento> TipoAlojamiento {
            get {
                return this.tipoAlojamientoField;
            }
            set {
                this.tipoAlojamientoField = value;
                this.RaisePropertyChanged("TipoAlojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> Habitacion1 {
            get {
                return this.habitacion1Field;
            }
            set {
                this.habitacion1Field = value;
                this.RaisePropertyChanged("Habitacion1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> Habitacion2 {
            get {
                return this.habitacion2Field;
            }
            set {
                this.habitacion2Field = value;
                this.RaisePropertyChanged("Habitacion2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> Habitacion3 {
            get {
                return this.habitacion3Field;
            }
            set {
                this.habitacion3Field = value;
                this.RaisePropertyChanged("Habitacion3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> Habitacion4 {
            get {
                return this.habitacion4Field;
            }
            set {
                this.habitacion4Field = value;
                this.RaisePropertyChanged("Habitacion4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> Habitacion5 {
            get {
                return this.habitacion5Field;
            }
            set {
                this.habitacion5Field = value;
                this.RaisePropertyChanged("Habitacion5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> Habitacion6 {
            get {
                return this.habitacion6Field;
            }
            set {
                this.habitacion6Field = value;
                this.RaisePropertyChanged("Habitacion6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<OrdenAlojamientos> Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("Nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NombreAlojamiento {
            get {
                return this.nombreAlojamientoField;
            }
            set {
                this.nombreAlojamientoField = value;
                this.RaisePropertyChanged("NombreAlojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int desayuno {
            get {
                return this.desayunoField;
            }
            set {
                this.desayunoField = value;
                this.RaisePropertyChanged("desayuno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int tarifaReembolsable {
            get {
                return this.tarifaReembolsableField;
            }
            set {
                this.tarifaReembolsableField = value;
                this.RaisePropertyChanged("tarifaReembolsable");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public enum OrdenAlojamientos {
        
        /// <remarks/>
        PorNombre,
        
        /// <remarks/>
        PorPrecio,
        
        /// <remarks/>
        PorCategoria,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionInfoAlojamiento : PeticionBase {
        
        private System.Guid idAlojamientoField;
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdAlojamiento {
            get {
                return this.idAlojamientoField;
            }
            set {
                this.idAlojamientoField = value;
                this.RaisePropertyChanged("IdAlojamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineltur.com/")]
    public partial class PeticionBuscarMisReservas : PeticionBase {
        
        private System.Guid userIdField;
        
        private int reservationCodeField;
        
        private string searchParameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ReservationCode {
            get {
                return this.reservationCodeField;
            }
            set {
                this.reservationCodeField = value;
                this.RaisePropertyChanged("ReservationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SearchParameter {
            get {
                return this.searchParameterField;
            }
            set {
                this.searchParameterField = value;
                this.RaisePropertyChanged("SearchParameter");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosSoapSoapChannel : CheckArgentina.LocalService.ServiciosSoapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosSoapSoapClient : System.ServiceModel.ClientBase<CheckArgentina.LocalService.ServiciosSoapSoap>, CheckArgentina.LocalService.ServiciosSoapSoap {
        
        public ServiciosSoapSoapClient() {
        }
        
        public ServiciosSoapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosSoapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CheckArgentina.LocalService.RespuestaLogin Login(CheckArgentina.LocalService.PeticionLogin peticion) {
            return base.Channel.Login(peticion);
        }
        
        public System.Threading.Tasks.Task<CheckArgentina.LocalService.RespuestaLogin> LoginAsync(CheckArgentina.LocalService.PeticionLogin peticion) {
            return base.Channel.LoginAsync(peticion);
        }
        
        public CheckArgentina.LocalService.RespuestaBuscarMisReservas BuscarMisReservas(CheckArgentina.LocalService.PeticionBuscarMisReservas peticion) {
            return base.Channel.BuscarMisReservas(peticion);
        }
        
        public System.Threading.Tasks.Task<CheckArgentina.LocalService.RespuestaBuscarMisReservas> BuscarMisReservasAsync(CheckArgentina.LocalService.PeticionBuscarMisReservas peticion) {
            return base.Channel.BuscarMisReservasAsync(peticion);
        }
        
        public CheckArgentina.LocalService.RespuestaInfoCuposSemanalesAlojamiento BuscarPreciosSemanalesHotel(CheckArgentina.LocalService.PeticionInfoAlojamiento peticion) {
            return base.Channel.BuscarPreciosSemanalesHotel(peticion);
        }
        
        public System.Threading.Tasks.Task<CheckArgentina.LocalService.RespuestaInfoCuposSemanalesAlojamiento> BuscarPreciosSemanalesHotelAsync(CheckArgentina.LocalService.PeticionInfoAlojamiento peticion) {
            return base.Channel.BuscarPreciosSemanalesHotelAsync(peticion);
        }
        
        public CheckArgentina.LocalService.RespuestaBuscarAlojamientosEInfo SearchHotels(CheckArgentina.LocalService.PeticionBuscarAlojamientos petition) {
            return base.Channel.SearchHotels(petition);
        }
        
        public System.Threading.Tasks.Task<CheckArgentina.LocalService.RespuestaBuscarAlojamientosEInfo> SearchHotelsAsync(CheckArgentina.LocalService.PeticionBuscarAlojamientos petition) {
            return base.Channel.SearchHotelsAsync(petition);
        }
    }
}
