'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3053
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization
Imports PriceWs.WSHCEV_ComplexTypes_1_0_1

Public Class WSHCEV_SimpleTypes_1_0_1



    '
    'Este código fuente fue generado automáticamente por xsd, Versión=2.0.50727.3038.
    '

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)> _
    Partial Public Class DateRangeWithDateType

        Private dateFromField As Date

        Private dateToField As Date

        '''<comentarios/>
        Public Property DateFrom() As Date
            Get
                Return Me.dateFromField
            End Get
            Set(ByVal value As Date)
                Me.dateFromField = value
            End Set
        End Property

        '''<comentarios/>
        Public Property DateTo() As Date
            Get
                Return Me.dateToField
            End Get
            Set(ByVal value As Date)
                Me.dateToField = value
            End Set
        End Property
    End Class

    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)> _
    Partial Public Class DateRangeWithDays

        Private dateFromField As UInteger

        Private dateToField As UInteger

        Private dateToFieldSpecified As Boolean

        '''<comentarios/>
        Public Property DateFrom() As UInteger
            Get
                Return Me.dateFromField
            End Get
            Set(ByVal value As UInteger)
                Me.dateFromField = value
            End Set
        End Property

        '''<comentarios/>
        Public Property DateTo() As UInteger
            Get
                Return Me.dateToField
            End Get
            Set(ByVal value As UInteger)
                Me.dateToField = value
            End Set
        End Property

        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DateToSpecified() As Boolean
            Get
                Return Me.dateToFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dateToFieldSpecified = value
            End Set
        End Property
    End Class


End Class